### ISSUE TITLE
Restore state at startup

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/Evergreen#134]

**Comment by brentsimmons** [comment]
Restore reader windows that were open, including window frames and splitview positions.

**Comment by brentsimmons** [comment]
Backing out of multiple windows for 1.0. Instead, restore main window at startup, including splitview position.

**Comment by tkrajacic** [comment]
Is there a specific reason not to use macOS' integrated mechanism for that? Sorry for the noise on closed issues.

[User Interface Preservation @ Apple docs](https://developer.apple.com/library/content/documentation/General/Conceptual/MOSXAppProgrammingGuide/CoreAppDesign/CoreAppDesign.html#//apple_ref/doc/uid/TP40010543-CH3-SW26)

**Comment by brentsimmons** [comment]
I haven’t actually learned how to use it yet, so I did it old school. Ideally it would use the built-in mechanism, yes.
