### ISSUE TITLE
Unread article counter not updating when feed is deleted

### ISSUE THREAD

**Issue by rex4539** [brentsimmons/Evergreen#173]
Git @ 48ca636

Reproducibility: always

Steps:
1. Refresh feeds to get some new articles.
2. Read all feeds except one.
3. Delete the unread feed.
4. Refresh feeds.

What happened:
Unread article counter is not updated.

![screen shot 2017-11-15 at 19 06 16](https://user-images.githubusercontent.com/227442/32849852-0bd09c18-ca39-11e7-8f1f-641259e76841.png)

Expected result:
Unread article counter is updated as soon as feed is deleted.

**Comment by brentsimmons** [comment]
Fixed in 1e713e3bfdfb30579e13be3259933f532ad0d5fe.
