### ISSUE TITLE
Character encoding issues in middle pane

### ISSUE THREAD

**Issue by rex4539** [brentsimmons/Evergreen#176]
Git @ 0e5b400

![screen shot 2017-11-16 at 09 00 03](https://user-images.githubusercontent.com/227442/32878293-1c620a6a-caae-11e7-9f91-b08a0347468f.png)

**Comment by brentsimmons** [comment]
I couldn’t reproduce this. What’s the exact URL you’re using for Daring Fireball?

**Comment by rex4539** [comment]
https://daringfireball.net/feeds/json

**Comment by brentsimmons** [comment]
This was a JSON Feed parser bug — it wasn’t decoding HTML entities. So this won’t appear as fixed until the various JSON Feeds in your feeds list have updated with new items.

**Comment by ePirat** [comment]
I am seeing the same problem (Version 1.0d25 (517)) 
<img width="1392" alt="Non-decoded HTML entity screenshot" src="https://user-images.githubusercontent.com/323210/34314459-364fc43e-e774-11e7-856b-533c2ba7884e.png">

Feed is http://www.manton.org/feed/json (the default one you get when downloading the App)

**Comment by brentsimmons** [comment]
It’s a bug in the feed. I’ve alerted Manton.
