### ISSUE TITLE
Codeblock HTML handling

### ISSUE THREAD

**Issue by ePirat** [brentsimmons/Evergreen#268]
In the most [recent post on NSHipster](http://nshipster.com/nsregularexpression/) I noticed some weird handlind of links in HTML code blocks:

<img width="582" alt="bildschirmfoto 2017-12-23 um 00 26 47" src="https://user-images.githubusercontent.com/323210/34314809-fea38e22-e777-11e7-8dfb-420f19a62585.png">

I am not sure if this is a problem in their feed or with Evergreens HTML rendering.

**Comment by brentsimmons** [comment]
It’s a bug in the feed, unfortunately.

(Evergreen uses WKWebView for rendering HTML, which is provided by the system. Same HTML rendering system Safari uses.)
