### ISSUE TITLE
Unsubscribe

### ISSUE THREAD

**Issue by sgoodwin** [brentsimmons/Evergreen#271]
I might be missing something, but it doesn't look like you can remove a feed. This would be a great feature.

**Comment by brentsimmons** [comment]
The Delete key, or Edit > Delete menu item, deletes a feed. (You can undo deleting a feed.)

**Comment by sgoodwin** [comment]
Oh, thanks! I didn't notice. Maybe a right-click menu for the items would also be helpful?

**Comment by brentsimmons** [comment]
Contextual menus are definitely on the to-do list. :)
