### ISSUE TITLE
Double posts after recent Evergreen commits

### ISSUE THREAD

**Issue by rex4539** [brentsimmons/Evergreen#281]
git @ 1d2d048

After some fairly recent (a couple of weeks ago or so) commit, I started getting double posts from many feeds.

It happens on some feeds and not in others.

![screen shot 2017-12-27 at 12 44 39](https://user-images.githubusercontent.com/227442/34379535-5f933428-eb04-11e7-8a41-b0752dcb3421.png)
![screen shot 2017-12-27 at 12 44 51](https://user-images.githubusercontent.com/227442/34379536-5fad55a6-eb04-11e7-931d-112d9cac7273.png)
![screen shot 2017-12-27 at 12 46 23](https://user-images.githubusercontent.com/227442/34379537-5fc6a0c4-eb04-11e7-99cf-bb2853649802.png)

**Comment by brentsimmons** [comment]
This was an unfortunate side effect of a bug fix. It will stop happening before long.
