### ISSUE TITLE
Mark All As Read not marking all selected folders as read

### ISSUE THREAD

**Issue by pberry** [brentsimmons/Evergreen#295]
Evergreen version 1.0d30 (522)
High Sierra version 10.13.2

When selecting multiple folders to mark them all as read from the toolbar button, only the last folder selected will be marked as read. I believe the intended/expected result would be that all folders selected would have all their feeds marked as read.

**Comment by pberry** [comment]
@brentsimmons should I file another issue for Mark All As Read working in Smart Feeds or that not intended functionality?

**Comment by brentsimmons** [comment]
That should be a separate issue. Thanks!
