### ISSUE TITLE
Sync via email

### ISSUE THREAD

**Issue by doerwalter** [brentsimmons/Evergreen#302]
I want to sync the "read" status of the articles between multiple devices, but I don't want to use any third-party services for that.

It would be great if Evergreen could sync the article status (and maybe even the list of feeds) by storing the configuration and read state in one or more emails that it puts on an IMAP server. Then I could configure each of my Evergreen instances to use the same email account and email folder to syncing.

**Comment by brentsimmons** [comment]
Writing an IMAP client for Evergreen would probably take me a year, so I won’t do this specifically. But I am considering CloudKit syncing for the future, which would allow for syncing without using one of the existing feed services.

**Comment by doerwalter** [comment]
Using CloudKit would still mean that the configuration is stored on Apple's servers, which is something, which I wouldn't want.

**Comment by doerwalter** [comment]
Would it be simpler to implement a generic documented sync API via HTTP? Then I could implement my own syncing backend.
