### ISSUE TITLE
Sign up - no response for much more than 7 days

### ISSUE THREAD

**Issue by Tubebuzzer** [brentsimmons/Evergreen#304]
Greetings,

I would really enjoy being a part of the steemit platform. I submitted my information what I think is quite a bit more than 7 days ago. Is it possible to get guidance if I need to take any action, if so what action?

Thank  you.

**Comment by brentsimmons** [comment]
You have the wrong place. This has nothing to do with steemit. (I don’t even know what steemit is.)
