### ISSUE TITLE
Project fails to build with Xcode 9.3 beta (9Q98q)

### ISSUE THREAD

**Issue by rex4539** [brentsimmons/Evergreen#313]
![screen shot 2018-01-28 at 01 51 02](https://user-images.githubusercontent.com/227442/35477554-1b2647d4-03ce-11e8-8e88-f260d72f4f09.png)

**Comment by danielpunkass** [comment]
@rex4539 I'll take a look at fixing this unless you had plans to do so.

**Comment by rex4539** [comment]
@danielpunkass My all means, go ahead :)

**Comment by danielpunkass** [comment]
Fixed by pull request #315.

**Comment by rex4539** [comment]
Verified.
