### ISSUE TITLE
Incorrect Title Links

### ISSUE THREAD

**Issue by wynnsyt** [brentsimmons/Evergreen#344]
Please see the screenshots below. In short, Evergreen shows an incorrect link for the item title. This may be a feed-specific issue but still, I've never had problems with other RSS readers. 

![screen shot 2018-02-13 at 2 54 44 pm](https://user-images.githubusercontent.com/2130881/36170790-6869ccb6-10ce-11e8-9eb5-5a671fddeed3.png)
![screen shot 2018-02-13 at 2 55 14 pm](https://user-images.githubusercontent.com/2130881/36170793-6a594bd2-10ce-11e8-8361-1fe9c75a12b2.png)

**Comment by brentsimmons** [comment]
What’s the URL of the feed?

**Comment by wynnsyt** [comment]
NSFW: https://www.tokyotosho.info/rss.php

**Comment by brentsimmons** [comment]
Evergreen is working as designed, in this case.

Here’s the deal: the feed specifies both a permalink (the guid) and a link. Evergreen uses the permalink (when it exists in the feed) over the link.

This is because we’ve found, in past experience, that this is what most people want most of the time.

**Comment by wynnsyt** [comment]
Isn't guid supposed to be an identifier and not necessarily a link? There is an attribute `isPermaLink` for the scenario you've described, but in this case the guid is not specified as link. It feels unintuitive that stuff between `<link>` is nowhere to be found in the item.

**Comment by brentsimmons** [comment]
Good question. A guid is a permalink by default. The feed can specify that it’s *not* a permalink, but the feed isn’t doing that. If it did, then Evergreen would use the link instead.

**Comment by wynnsyt** [comment]
Ah I wasn't aware that guid is permalink by default. Thanks for the explanation.
