### ISSUE TITLE
Special case for JSON Feed feeds like Kottke’s where the title includes HTML entities

### ISSUE THREAD

**Issue by meissnem** [brentsimmons/Evergreen#346]
I subscribe to the JSON Feed of Kottke's site <https://feeds.kottke.org/json>.

When his post titles contain smart quotes, his feed has them as character entities rather than UTF-8 encoded characters. Evergreen renders the entities rather than expanding them.

![kottke](https://user-images.githubusercontent.com/868308/36231708-b0379704-11a4-11e8-9aff-15c06dd49ce6.png)

(I see the JSON Feed spec says that item titles should be plain text, so it would be completely reasonable to close this since it works as designed)

**Comment by brentsimmons** [comment]
Also needed for Nick Heer’s feed at pxlnv.com/json
