### ISSUE TITLE
Weird rendering

### ISSUE THREAD

**Issue by rex4539** [brentsimmons/Evergreen#409]
http://www.gfc.gr/el/info-center/news/1870-ξεχωριστή-παρουσία-του-ελληνικού-κινηματογράφου-σε-σημαντικά-διεθνή-φεστιβάλ.html

![screen shot 2018-08-28 at 00 39 33](https://user-images.githubusercontent.com/227442/44687841-ffc9e480-aa5a-11e8-8dc5-6e86b6efa4c4.png)

**Comment by brentsimmons** [comment]
What’s the URL of the feed?

**Comment by rex4539** [comment]
http://www.gfc.gr/el/info-center/news.feed?type=rss

**Comment by danielpunkass** [comment]
It looks like the issue only affects the latest post in that feed, where each of the affected paragraphs has an inline CSS style specifying that the background should be explicitly "white":

<span style="font-size: 12pt; line-height: 115%; font-family: arial, helvetica, sans-serif; background: white;">

If the style of the content is going to impose a specific background color then it should probably also take pains to impose a specific foreground color that will look good. In NetNewsWire, the rendering in this example defaults to a dark background with light text, but the inline style only overrides one of those. If I manually disable the white background on just the first paragraph, you can see how it's improved.

<img width="1026" alt="2018-08-28 at 2 58 pm" src="https://user-images.githubusercontent.com/14606/44744430-20ce1c00-aad3-11e8-9b8c-bafc4414e66d.png">

The other posts in this feed seem fine, so I think what happened is probably whoever wrote that most recent article pasted some paragraphs in from another source and inadvertently brought hard-coded styles along with the pasted text.
