### ISSUE TITLE
Evergreen News feed URL may be wrong

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/Evergreen#73]

**Comment by ap** [comment]
I know this is not a great place to report this particular issue, but I’m not finding a better venue in a pinch, so here goes:

The Evergreen blog itself does not have any `<link rel="alternate">` tags, nor any regular links to its feeds, so <http://ranchero.com/evergreen/feed.json> can only be found by digging around in this here repository, and <http://ranchero.com/evergreen/xml/rss.xml> is completely undiscoverable. (I found it by guessing based on the inessential.com RSS URL.)
